#!/bin/bash
set -e
cd "$(dirname -- "${BASH_SOURCE[0]}")/.."

MODELS_ARCHIVE='hackathon2025.tar.xz'
REPOS_FILE='repositories'

if [[ -r '.env' ]] ; then
    eval $(grep -v '^[UG]ID=' .env)
fi


add_variable_to_env_file() {
    if ! grep -q "$1=" .env 2>/dev/null ; then
        echo "  - Add $1=$2 to .env"
        echo "$1=$2" >>.env
    fi
}

initialize_env_file() {
    echo 'Initialize ".env" file'
    add_variable_to_env_file UID "$(id -u)"
    add_variable_to_env_file GID "$(id -g)"
    add_variable_to_env_file USER "$(whoami)"
    add_variable_to_env_file WORKSPACE "$(pwd)"
}

import_packages() {
    echo 'Import packages'
    vcs import --force --recursive -w6 <"docker/$REPOS_FILE"
}

import_gazebo_models() {
    echo 'Import gazebo models'
    mkdir -p gazebo
    
    nextcloud_download='https://nextcloud.inrae.fr/s/4PRo8ebgiLyf788/download'
    archive_hash="${MODELS_ARCHIVE}.sha1"
    remote_hash="/tmp/${archive_hash}"
    local_hash="gazebo/${archive_hash}"
    archive="/tmp/${MODELS_ARCHIVE}"

    echo "  download hash (${archive_hash})"
    wget -q -O "${remote_hash}" "${nextcloud_download}?path=%2F&files=${archive_hash}"

    # download archive only if the remote hash differs from the local one
    if [[ ! -r "${local_hash}" ]] || ! cmp -s "${remote_hash}" "${local_hash}" ; then
        wget -O "${archive}" "${nextcloud_download}?path=%2F&files=${MODELS_ARCHIVE}"
        if tar -C gazebo -xvf "${archive}" ; then
            mv -f "${remote_hash}" "${local_hash}"
        else
            rm "${remote_hash}"
        fi
        rm "${archive}"
    else
        echo "  models are up-to-date"
        rm "${remote_hash}"
    fi
}


initialize_env_file
import_packages
import_gazebo_models
echo 'Installation completed successfully'
